import type { Metadata } from "next";
import { StoreProvider } from "./StoreProvider"; // özel bileşenini kullandık
import "./globals.css";
import Navbar from "./components/Navbar";

// Sunucu tarafında metadata tanımlanıyor
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <div className="flex flex-col">
            <Navbar />
            {children}
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
